apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-worker
  labels:
    app: {{ .Values.worker.labels.app }}
spec:
  selector:
    app: {{ .Values.worker.labels.app }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
