replicaCount: 1

image:
  repository: dockersamples/examplevotingapp_vote
  tag: before
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80

labels:
  app: vote
